#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    M_UP_DIR = SAFE_RANGE,
    M_THE,
    M_MENT,
    M_UEN,
    M_ENT,
    M_ION,
    M_ON,
    M_BASE_SPC,
    M_ALT_SPC,
    M_BASE_ENT,
    M_ALT_ENT
};

// Combos
// Right mods
const uint16_t PROGMEM c_hj[] = {KC_H, KC_J, COMBO_END};
const uint16_t PROGMEM c_fg[] = {KC_F, KC_G, COMBO_END};

combo_t key_combos[] = {
    COMBO(c_hj, KC_ENT),
    COMBO(c_fg, KC_SPC),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Main
	[0] = LAYOUT_split_3x5_2(
        KC_Q, KC_W, KC_E, KC_R, KC_T,                                       KC_Y, KC_U, KC_I, KC_O, KC_P,
        KC_A, KC_S, KC_D, KC_F, KC_G,                                       KC_H, KC_J, KC_K, KC_L, KC_SCLN,
        LSFT_T(KC_Z), LCTL_T(KC_X), LALT_T(KC_C), LGUI_T(KC_V), KC_B,       KC_N, RGUI_T(KC_M), RALT_T(KC_COMM), RCTL_T(KC_DOT), RSFT_T(KC_SLSH),
                                              MO(2) , KC_SPC,            KC_ENT, MO(3)
    ),
    // Alternative - Sturdy
	[1] = LAYOUT_split_3x5_2(
        KC_V, KC_M, KC_L, KC_C, KC_P,                                   KC_X, KC_F, KC_O, KC_U, KC_J,
        KC_S, KC_T, KC_R, KC_D, KC_Y,                                   KC_DOT, KC_N, KC_A, KC_E, KC_I,
        LSFT_T(KC_Z), LCTL_T(KC_K), LALT_T(KC_Q), LGUI_T(KC_G), KC_W,   KC_B, RGUI_T(KC_H), RALT_T(KC_QUOT), RCTL_T(KC_SCLN), RSFT_T(KC_COMM),
                                              MO(2) , KC_SPC,       KC_ENT, MO(3)
    ),
    // Numbers/Symbols
	[2] = LAYOUT_split_3x5_2(
        TO(1), TO(2), KC_TRNS, KC_BSLS, KC_LBRC,                    KC_RBRC, KC_1, KC_2, KC_3, KC_TRNS,
        KC_PIPE, KC_GRV, KC_TAB, KC_ESC, KC_LPRN,                   KC_RPRN, KC_4, KC_5, KC_6, KC_0,
        KC_KB_VOLUME_DOWN, KC_KB_VOLUME_UP, LCTL(LALT(LGUI(KC_SPC))), LSFT(LGUI(KC_V)), KC_LCBR,       KC_RCBR, KC_7, KC_8, KC_9, KC_DOT,
                                    KC_TRNS, KC_TRNS,           KC_DEL, KC_LSFT
    ),
    // Nav/Symbols
	[3] = LAYOUT_split_3x5_2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                KC_HOME,  KC_PGDN, KC_PGUP, KC_END, KC_QUOT,
        KC_MINS, KC_PLUS, KC_UNDS, KC_EQL, KC_UNDS,                 KC_LEFT,  KC_DOWN, KC_UP, KC_RIGHT, KC_DQT,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                KC_TRNS, KC_PRINT_SCREEN, KC_TRNS, KC_TRNS, KC_TRNS,
                                    KC_TRNS, KC_BSPC,              KC_TRNS, KC_TRNS
    ),
    // Mods
	[4] = LAYOUT_split_3x5_2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), KC_TRNS,                       KC_TRNS, OSM(MOD_RGUI), OSM(MOD_RALT), OSM(MOD_RCTL), OSM(MOD_RSFT),
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                                    KC_TRNS, KC_DEL,                         KC_TRNS, KC_TRNS
    ),
    // Left Mods
	[5] = LAYOUT_split_3x5_2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                                    KC_TRNS, KC_TRNS,                         KC_ENT, KC_TRNS
    ),
	[6] = LAYOUT_split_3x5_2(
        KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS,              KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_0, KC_1, KC_2, KC_3, KC_PMNS,                    KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS,
        KC_PAST, KC_4, KC_5, KC_6, KC_PEQL,                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                                    KC_TRNS, KC_TRNS,           KC_TRNS, KC_TRNS
    )
};

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
    switch (keycode) {
        case M_UP_DIR: SEND_STRING("./"); break;
        case M_THE: SEND_STRING("the"); break;
        case M_MENT: SEND_STRING("ment"); break;
        case M_UEN: SEND_STRING("uen"); break;
        case M_ENT: SEND_STRING("ent"); break;
        case M_ION: SEND_STRING("ion"); break;
        case M_ON: SEND_STRING("on"); break;
    }
    return true;
}

uint16_t get_alt_repeat_key_keycode_user(uint16_t keycode, uint8_t mods) {
    /* bool shifted = (mods & MOD_MASK_SHIFT);  // Was Shift held? */
    /* bool ctrl = (mods & MOD_MASK_CTRL); */
    /* bool alt = (mods & MOD_MASK_ALT); */
    /* bool GUI = (mods & MOD_MASK_GUI); */
    switch (keycode) {
        case KC_A: return KC_O;
        case KC_C: return KC_Y;
        case KC_D: return KC_Y;
        case KC_E: return KC_U;
        case KC_G: return KC_Y;
        case KC_I: return M_ON;
        case KC_L: return KC_K;
        case KC_M: return M_ENT;
        case KC_N: return M_ION;
        case KC_O: return KC_A;
        case KC_P: return KC_Y;
        case KC_Q: return M_UEN;
        case KC_R: return KC_L;
        case KC_S: return KC_K;
        case KC_T: return M_MENT;
        case KC_U: return KC_E;
        case KC_Y: return KC_P;
        case KC_SPC: return M_THE;
        case KC_DOT: return M_UP_DIR;
    }

    return KC_TRNS;
}

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
