#include QMK_KEYBOARD_H

// Combos
const uint16_t PROGMEM c_hj[] = {KC_H, RGUI_T(KC_J), COMBO_END};
const uint16_t PROGMEM c_fg[] = {LGUI_T(KC_F), KC_G, COMBO_END};
const uint16_t PROGMEM c_yu[] = {KC_Y, KC_U, COMBO_END};

combo_t key_combos[] = {
    COMBO(c_hj, KC_ENT),
    COMBO(c_fg, KC_SPC),
    COMBO(c_yu, LALT(KC_Y)), // tmux scrollback
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Main
    [0] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, LSFT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), KC_G, KC_H, RGUI_T(KC_J), RALT_T(KC_K), RCTL_T(KC_L), RSFT_T(KC_SCLN), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, MO(2), KC_SPC, KC_ENT, MO(3)),
    // Alternative - Sturdy
    [1] = LAYOUT_split_3x5_2(KC_V, KC_M, KC_L, KC_C, KC_P, KC_X, KC_F, KC_O, KC_U, KC_J, LSFT_T(KC_S), LCTL_T(KC_T), LALT_T(KC_R), LGUI_T(KC_D), KC_Y, KC_DOT, RGUI_T(KC_N), RALT_T(KC_A), RCTL_T(KC_E), RSFT_T(KC_I), KC_Z, KC_K, KC_Q, KC_G, KC_W, KC_B, KC_H, KC_QUOT, KC_SCLN, KC_COMM, MO(2), KC_SPC, KC_ENT, MO(3)),
    // Numbers/Symbols
    [2] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_BSLS, KC_LBRC, KC_RBRC, KC_1, KC_2, KC_3, KC_TRNS, KC_PIPE, KC_GRV, KC_TAB, KC_ESC, KC_LPRN, KC_RPRN, KC_4, KC_5, KC_6, KC_0, KC_KB_VOLUME_DOWN, KC_KB_VOLUME_UP, KC_MPLY, KC_MUTE, KC_LCBR, KC_RCBR, KC_7, KC_8, KC_9, KC_DOT, KC_TRNS, KC_TRNS, KC_DEL, KC_LSFT),
    // Nav/Symbols
    [3] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_QUOT, KC_MINS, KC_PLUS, KC_UNDS, KC_EQL, KC_UNDS, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_DQT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PRINT_SCREEN, KC_TRNS, KC_TRNS, KC_TRNS, MO(4), KC_BSPC, KC_TRNS, KC_TRNS),
    // F-Keys + System
    [4] = LAYOUT_split_3x5_2(QK_BOOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F10, TO(0), TO(1), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    // Left Mods
    [5] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ENT, KC_TRNS),
    // Numpad
    [6] = LAYOUT_split_3x5_2(KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_1, KC_2, KC_3, KC_PMNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_PAST, KC_4, KC_5, KC_6, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)};
