#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    M_UP_DIR = SAFE_RANGE,
    M_THE,
    M_MENT,
    M_UEN,
    M_ENT,
    M_ION,
    M_ON
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Main
	[0] = LAYOUT_split_3x5_2(
        KC_Q, KC_W, KC_E, KC_R, KC_T,                                KC_Y, KC_U, KC_I, KC_O, KC_P,
    LSFT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), KC_G,      KC_H, RGUI_T(KC_J), RALT_T(KC_K), RCTL_T(KC_L), RSFT_T(KC_SCLN),
        KC_Z, KC_X, KC_C, KC_V, KC_B,                                KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
                                              MO(2) , KC_SPC,       KC_ENT, MO(3)
    ),
    // Alternative - Sturdy
	[1] = LAYOUT_split_3x5_2(
        KC_V, KC_M, KC_L, KC_C, KC_P,                                   KC_B, QK_ALT_REPEAT_KEY, KC_O, KC_U, KC_B,
    LSFT_T(KC_S), LCTL_T(KC_T), LALT_T(KC_R), LGUI_T(KC_D), KC_Y,       KC_F, RGUI_T(KC_N), RALT_T(KC_A), RCTL_T(KC_E), RSFT_T(KC_I),
        KC_X, KC_K, KC_J, KC_G, KC_W,                                   KC_Z, KC_H, KC_COMM, KC_DOT, KC_SCLN,
                                              MO(2) , KC_SPC,       KC_ENT, MO(3)
    ),
    // Numbers/Symbols
	[2] = LAYOUT_split_3x5_2(
        TO(1), TO(2), KC_TRNS, KC_BSLS, KC_LBRC,                KC_RBRC, KC_1, KC_2, KC_3, KC_TRNS,
        KC_PIPE, KC_GRV, KC_TAB, KC_ESC, KC_LPRN,                  KC_RPRN, KC_4, KC_5, KC_6, KC_0,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCBR,                 KC_RCBR, KC_7, KC_8, KC_9, KC_TRNS,
                                    KC_TRNS, KC_TRNS,           KC_DEL, KC_LSFT
    ),
    // Nav/Symbols
	[3] = LAYOUT_split_3x5_2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                KC_HOME,  KC_PGDN, KC_PGUP, KC_END, KC_QUOT,
        KC_MINS, KC_PLUS, KC_UNDS, KC_EQL, KC_UNDS,                  KC_LEFT,  KC_DOWN, KC_UP, KC_RIGHT, KC_DQT,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                                    KC_TRNS, KC_BSPC,              KC_TRNS, KC_TRNS
    ),
	[4] = LAYOUT_split_3x5_2(
        KC_TRNS, KC_COLN, KC_LT, KC_GT, KC_SCLN,                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT,                  KC_TRNS, KC_NO, KC_EQL, KC_PLUS, KC_PERC,
        KC_TRNS, KC_EXLM, KC_LBRC, KC_RBRC, KC_TRNS,                KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                                    KC_VOLD, KC_TRNS,           KC_TRNS, KC_VOLU
    ),
	[5] = LAYOUT_split_3x5_2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10,
        KC_TRNS, KC_NO, LCTL(KC_LALT), KC_TRNS,                     KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6,
        KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                 KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3,
                                    KC_F12, KC_TRNS,            KC_TRNS, KC_TRNS
        , KC_TRNS),
	[6] = LAYOUT_split_3x5_2(
        KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS,              KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_0, KC_1, KC_2, KC_3, KC_PMNS,                    KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS,
        KC_PAST, KC_4, KC_5, KC_6, KC_PEQL,                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                                    KC_TRNS, KC_TRNS,           KC_TRNS, KC_TRNS
    )
};

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
    switch (keycode) {
        case M_UP_DIR: SEND_STRING("./"); break;
        case M_THE: SEND_STRING("the"); break;
        case M_MENT: SEND_STRING("ment"); break;
        case M_UEN: SEND_STRING("uen"); break;
        case M_ENT: SEND_STRING("ent"); break;
        case M_ION: SEND_STRING("ion"); break;
        case M_ON: SEND_STRING("on"); break;
    }
    return true;
}

uint16_t get_alt_repeat_key_keycode_user(uint16_t keycode, uint8_t mods) {
    /* bool shifted = (mods & MOD_MASK_SHIFT);  // Was Shift held? */
    /* bool ctrl = (mods & MOD_MASK_CTRL); */
    /* bool alt = (mods & MOD_MASK_ALT); */
    /* bool GUI = (mods & MOD_MASK_GUI); */
    switch (keycode) {
        case KC_A: return KC_O;
        case KC_C: return KC_Y;
        case KC_D: return KC_Y;
        case KC_E: return KC_U;
        case KC_G: return KC_Y;
        case KC_I: return M_ON;
        case KC_L: return KC_K;
        case KC_M: return M_ENT;
        case KC_N: return M_ION;
        case KC_O: return KC_A;
        case KC_P: return KC_Y;
        case KC_Q: return M_UEN;
        case KC_R: return KC_L;
        case KC_S: return KC_K;
        case KC_T: return M_MENT;
        case KC_U: return KC_E;
        case KC_Y: return KC_P;
        case KC_SPC: return M_THE;
        case KC_DOT: return M_UP_DIR;
    }

    return KC_TRNS;
}

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)





